#!/usr/bin/env bash
#script to configuire web server

#install nginx
apt-get -y update
apt-get -y install nginx
service nginx start

HEADER="\\\n\tadd_header X-Served-By $(hostname);"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
	sed -i "24i $HEADER" /etc/nginx/sites-available/default
fi
# create a first index.html page
echo "Hello World!" > /var/www/html/index.html

FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sed -i "50i $STRING" /etc/nginx/sites-available/default
fi

FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "46i $ERROR" /etc/nginx/sites-available/default
fi

service nginx restart
