#!/usr/bin/env bash
#  Run Nginx as Nginx  
chmod ugo+wrx /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx reload
sudo -u nginx service nginx restart
